package OopProject;

import java.awt.print.PrinterException; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author MBG Traders
 */
public class Customers extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ArrayList<User> usersArray = new ArrayList<>();
    public Customers() {
        initComponents();
        showUsersInTable();
    }
   
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        C_contact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        C_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        C_firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        C_address = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_database = new javax.swing.JTable();
        C_lastname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonupdate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4Delete = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jButtonadd = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BORSA RESTAURANT ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 560, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Desktop\\Resturant_Project\\src\\OopProject\\images\\shop-4806610_1280.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1290, 50));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER'S CONTACT");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 287, 42));
        jPanel4.add(C_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 380, 42));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CUSTOMER ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 228, 42));
        jPanel4.add(C_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 380, 42));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CUSTOMER LAST NAME");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 300, 42));

        C_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_firstnameActionPerformed(evt);
            }
        });
        jPanel4.add(C_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 380, 42));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CUSTOMER'S ADDRESS");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 287, 42));
        jPanel4.add(C_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 380, 42));

        jTable_database.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Cust_fname", "Cust_lname", "Address", "Contact_no"
            }
        ));
        jScrollPane1.setViewportView(jTable_database);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 770, 200));

        C_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_lastnameActionPerformed(evt);
            }
        });
        jPanel4.add(C_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 380, 42));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CUSTOMER FIRST NAME");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 67, 300, 42));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Desktop\\Resturant_Project\\src\\OopProject\\images\\adult-2178440_1280.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 420));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonupdate.setBackground(new java.awt.Color(0, 0, 0));
        jButtonupdate.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonupdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonupdate.setText("UPDATE");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 200, 53));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 200, 53));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 53));

        jButton4Delete.setBackground(new java.awt.Color(0, 0, 0));
        jButton4Delete.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton4Delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Delete.setText("DELETE");
        jButton4Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4DeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 210, 53));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel3.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 220, 53));

        jButtonadd.setBackground(new java.awt.Color(0, 0, 0));
        jButtonadd.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButtonadd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonadd.setText("ADD NEW");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, 53));

        exitbtn.setBackground(new java.awt.Color(0, 0, 0));
        exitbtn.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel3.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 220, 53));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Desktop\\Resturant_Project\\src\\OopProject\\images\\shop-4806610_1280.jpg")); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 880));

        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 870));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_firstnameActionPerformed

    private void C_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_lastnameActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:0+
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
        if(checkEmptyFields())
        {
            int id = Integer.valueOf(C_id.getText());
            String firstname = C_firstname.getText();
            String lastname = C_lastname.getText();
            String address = C_address.getText();
            int contactno = Integer.valueOf(C_contact.getText());

            String insertQuery = "INSERT INTO `costumer_data`(`Cust_id`, `Cust_Firstname`, `Cust_Lastname`, `Cust_address`, `Contact_no`) VALUES (?,?,?,?,?)";

            try {

                PreparedStatement ps = Connect.getconnection().prepareStatement(insertQuery);
                ps.setInt(1, id);
                ps.setString(2, firstname);
                ps.setString(3, lastname);
                ps.setString(4, address);
                ps.setInt(5, contactno);

                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "New Customer Added Successfully", "Add Customer", JOptionPane.INFORMATION_MESSAGE);
                    Customers ct = new Customers();
                    ct.setVisible(true);
                    ct.pack();
                    ct.setLocationRelativeTo(null);
                    this.dispose();
                    System.out.println("New Customer Added");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Customer Not Added", "Add Customer", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Some Error Message Here");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty", "Add Customer", JOptionPane.ERROR_MESSAGE);
            System.out.println("One Or More Fields Are Empty");
        }
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        admin_page ap = new admin_page();
        ap.show();
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            jTable_database.print();
        } catch (PrinterException ex) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        C_id.setText("");
        C_firstname.setText("");
        C_lastname.setText("");
        C_address.setText("");
        C_contact.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        if(checkEmptyFields())
        {
            int id = Integer.valueOf(C_id.getText());
            String firstname = C_firstname.getText();
            String lastname = C_lastname.getText();
            String address = C_address.getText();
            int contactno = Integer.valueOf(C_contact.getText());

            String updateQuery = "UPDATE `costumer_data` SET `Cust_Firstname`=?,`Cust_Lastname`=?,`Cust_address`=?,`Contact_no`=? WHERE `Cust_id`=?";

            try {

                PreparedStatement ps = Connect.getconnection().prepareStatement(updateQuery);

                ps.setString(1, firstname);
                ps.setString(2, lastname);
                ps.setString(3, address);
                ps.setInt(4, contactno);
                ps.setInt(5, id);

                if(ps.executeUpdate() > 0)
                {
                    showUsersInTable();
                    JOptionPane.showMessageDialog(null, "Customer Updated", "Edit Customer", JOptionPane.INFORMATION_MESSAGE);
                    Customers ct = new Customers();
                    ct.setVisible(true);
                    ct.pack();
                    ct.setLocationRelativeTo(null);
                    this.dispose();
                    System.out.println("New Customer Added");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Customer Not Updated", "Edit Customer", JOptionPane.ERROR_MESSAGE);
                    //System.out.println("Some Error Message Here");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty", "Edit Customer", JOptionPane.ERROR_MESSAGE);
            System.out.println("One Or More Fields Are Empty");
        }
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jButton4DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4DeleteActionPerformed
        // TODO add your handling code here:
         if(checkEmptyFields())
        {
            int id = Integer.valueOf(C_id.getText());
            String firstname = C_firstname.getText();
            String lastname = C_lastname.getText();
            String address = C_address.getText();
            int contactno = Integer.valueOf(C_contact.getText());

            String DeleteQuery =  "Delete from costumer_data where Cust_id =?";

            try {

                PreparedStatement ps = Connect.getconnection().prepareStatement(DeleteQuery);

                ps.setString(1, firstname);
                ps.setString(2, lastname);
                ps.setString(3, address);
                ps.setInt(4, contactno);
                ps.setInt(5, id);

                if(ps.executeUpdate() > 0)
                {
                    showUsersInTable();
                    JOptionPane.showMessageDialog(null, " DATA DELETED ", "SUCCESSFULLY", JOptionPane.INFORMATION_MESSAGE);
                    Customers ct = new Customers();
                    ct.setVisible(true);
                    ct.pack();
                    ct.setLocationRelativeTo(null);
                    this.dispose();
                    System.out.println(" DELETED ");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Data not Deleted", "Delete again", JOptionPane.ERROR_MESSAGE);
                    //System.out.println("Some Error Message Here");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    
                                                 

    }//GEN-LAST:event_jButton4DeleteActionPerformed
    
    public ArrayList<User> getUserList()
    {
        ArrayList<User> list = new ArrayList<>();
        String query = "SELECT * FROM costumer_data";
        
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps = Connect.getconnection().prepareStatement(query);
            rs = ps.executeQuery();
            User user;
            
            while(rs.next())
            {
                user = new User(rs.getInt("Cust_id"), rs.getString("Cust_Firstname"), 
                                      rs.getString("Cust_Lastname"), rs.getString("Cust_address"),
                                      rs.getInt("Contact_no"));
                list.add(user);
                
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
        
        usersArray = list;
        return list;
        
    }
    
    // create a function to show products in table
    public final void showUsersInTable()
    {
        ArrayList<User> usersList = getUserList();
        DefaultTableModel model = (DefaultTableModel) jTable_database.getModel();
        
        // clear jtable
        model.setRowCount(0);
        
        Object[] row = new Object[5];// 5 the number of columns
        
        for(int i = 0; i < usersList.size(); i++)
        {
            row[0] = usersList.get(i).getId();
            row[1] = usersList.get(i).getFirstname();
            row[2] = usersList.get(i).getLastname();
            row[3] = usersList.get(i).getAddress();
            row[4] = usersList.get(i).getContactno();
            
            
            model.addRow(row);
        }
    }
    
    public boolean checkEmptyFields()
    {
        String id = C_id.getText().trim();
        String firstname = C_lastname.getText().trim();
        String lastname = C_firstname.getText().trim();
        String address = C_address.getText().trim();
        String contactno = C_contact.getText().trim();
        
        if(id.equals("") || firstname.equals("") || lastname.equals("") || address.equals("") || contactno.equals(""))
        {
            return false;
          // if one or more fields are empty return false else return true
        }
        else
        {
          return true;    
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Customers().setVisible(true);
            }
        });
  
}   
    
  

  
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C_address;
    private javax.swing.JTextField C_contact;
    private javax.swing.JTextField C_firstname;
    private javax.swing.JTextField C_id;
    private javax.swing.JTextField C_lastname;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4Delete;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_database;
    // End of variables declaration//GEN-END:variables
}
