package OopProject;




import java.awt.Component;
import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
  * @author MBG Traders
 */
public class OO_Resturant extends javax.swing.JFrame {

    /**
     * Creates new form OO_Resturant
     */
    public OO_Resturant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Meal_Panel = new javax.swing.JPanel();
        BurgerQty = new javax.swing.JTextField();
        jlbdChicLegend = new javax.swing.JLabel();
        jlbdBurMeal = new javax.swing.JLabel();
        BurgMealQty = new javax.swing.JTextField();
        ZingerQty = new javax.swing.JTextField();
        jlbdFish = new javax.swing.JLabel();
        jlbdTax6 = new javax.swing.JLabel();
        jlbdChBurg = new javax.swing.JLabel();
        ChLegQty = new javax.swing.JTextField();
        jlbdCheese = new javax.swing.JLabel();
        BacCheQty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Drink_Panel = new javax.swing.JPanel();
        jlbdTax3 = new javax.swing.JLabel();
        jlbdMilkShake = new javax.swing.JLabel();
        MilkQty = new javax.swing.JTextField();
        VanQty = new javax.swing.JTextField();
        jlbdVanCone = new javax.swing.JLabel();
        jlbdClassicVAn = new javax.swing.JLabel();
        ClasVan = new javax.swing.JTextField();
        VanMilkQty = new javax.swing.JTextField();
        ChocMilkQty = new javax.swing.JTextField();
        jlbdChShake = new javax.swing.JLabel();
        jlbdVanShake = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cost_panel = new javax.swing.JPanel();
        jlbdCostMealText = new javax.swing.JLabel();
        jlbdCostDrinkText = new javax.swing.JLabel();
        jlbdCostMadeText = new javax.swing.JLabel();
        TotalCostShow = new javax.swing.JTextField();
        CostDrinkShow = new javax.swing.JTextField();
        CostMealShow = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Payment_panel = new javax.swing.JPanel();
        TaxShow = new javax.swing.JTextField();
        SubTotalShow = new javax.swing.JTextField();
        TotalShow = new javax.swing.JTextField();
        jlbdSubTotal = new javax.swing.JLabel();
        jlbdTotal = new javax.swing.JLabel();
        jlbdTax2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Receipt_Panel = new javax.swing.JTextArea();
        jBut_Save = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jBut_Total = new javax.swing.JButton();
        jBut_Receipt = new javax.swing.JButton();
        jBut_Reset = new javax.swing.JButton();
        jBut_Back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 12));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BORSA RESTAURANT ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1386, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 120));

        Meal_Panel.setBackground(new java.awt.Color(0, 102, 102));
        Meal_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        Meal_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BurgerQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BurgerQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BurgerQty.setText("0");
        BurgerQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgerQtyActionPerformed(evt);
            }
        });
        Meal_Panel.add(BurgerQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 91, 67, -1));

        jlbdChicLegend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdChicLegend.setForeground(new java.awt.Color(255, 255, 255));
        jlbdChicLegend.setText("Chicken Legend Burger 300/=");
        Meal_Panel.add(jlbdChicLegend, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 125, 312, 28));

        jlbdBurMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdBurMeal.setForeground(new java.awt.Color(255, 255, 255));
        jlbdBurMeal.setText("Chicken Cheese Burger 350/=");
        Meal_Panel.add(jlbdBurMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 159, 286, 28));

        BurgMealQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BurgMealQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BurgMealQty.setText("0");
        BurgMealQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgMealQtyActionPerformed(evt);
            }
        });
        Meal_Panel.add(BurgMealQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 159, 67, -1));

        ZingerQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ZingerQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ZingerQty.setText("0");
        ZingerQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZingerQtyActionPerformed(evt);
            }
        });
        Meal_Panel.add(ZingerQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 57, 67, -1));

        jlbdFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdFish.setForeground(new java.awt.Color(255, 255, 255));
        jlbdFish.setText("Zinger Burger     350/= ");
        Meal_Panel.add(jlbdFish, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 57, 244, 28));

        jlbdTax6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdTax6.setForeground(new java.awt.Color(255, 255, 255));
        jlbdTax6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbdTax6.setText("BURGERS");
        Meal_Panel.add(jlbdTax6, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 23, 116, 28));

        jlbdChBurg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdChBurg.setForeground(new java.awt.Color(255, 255, 255));
        jlbdChBurg.setText("Zinger Cheese Burger  450/=");
        Meal_Panel.add(jlbdChBurg, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 91, 312, 28));

        ChLegQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ChLegQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChLegQty.setText("0");
        ChLegQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChLegQtyActionPerformed(evt);
            }
        });
        Meal_Panel.add(ChLegQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 125, 67, -1));

        jlbdCheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdCheese.setForeground(new java.awt.Color(255, 255, 255));
        jlbdCheese.setText("Bacon & Cheese Burger 400/=");
        Meal_Panel.add(jlbdCheese, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 193, -1, 28));

        BacCheQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BacCheQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BacCheQty.setText("0");
        BacCheQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacCheQtyActionPerformed(evt);
            }
        });
        Meal_Panel.add(BacCheQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 193, 67, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Desktop\\Resturant_Project\\src\\OopProject\\images\\abstract-1238247_640.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        Meal_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 230));

        getContentPane().add(Meal_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 460, 250));

        Drink_Panel.setBackground(new java.awt.Color(0, 102, 102));
        Drink_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        Drink_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbdTax3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdTax3.setForeground(new java.awt.Color(255, 255, 255));
        jlbdTax3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbdTax3.setText("DRINKS & SHAKES");
        Drink_Panel.add(jlbdTax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 23, 265, 28));

        jlbdMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdMilkShake.setForeground(new java.awt.Color(255, 255, 255));
        jlbdMilkShake.setText("Milk Shake   150/=");
        Drink_Panel.add(jlbdMilkShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 57, -1, 28));

        MilkQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MilkQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MilkQty.setText("0");
        MilkQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkQtyActionPerformed(evt);
            }
        });
        Drink_Panel.add(MilkQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 57, 71, -1));

        VanQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VanQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VanQty.setText("0");
        VanQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanQtyActionPerformed(evt);
            }
        });
        Drink_Panel.add(VanQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 91, 71, -1));

        jlbdVanCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdVanCone.setForeground(new java.awt.Color(255, 255, 255));
        jlbdVanCone.setText("Choclate Shake 200/=");
        Drink_Panel.add(jlbdVanCone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 193, 272, 28));

        jlbdClassicVAn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdClassicVAn.setForeground(new java.awt.Color(255, 255, 255));
        jlbdClassicVAn.setText("Special Oreo Shake   300/=");
        Drink_Panel.add(jlbdClassicVAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 91, 272, 28));

        ClasVan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClasVan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ClasVan.setText("0");
        ClasVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasVanActionPerformed(evt);
            }
        });
        Drink_Panel.add(ClasVan, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 125, 71, -1));

        VanMilkQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VanMilkQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VanMilkQty.setText("0");
        VanMilkQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VanMilkQtyActionPerformed(evt);
            }
        });
        Drink_Panel.add(VanMilkQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 159, 71, -1));

        ChocMilkQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ChocMilkQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ChocMilkQty.setText("0");
        ChocMilkQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocMilkQtyActionPerformed(evt);
            }
        });
        Drink_Panel.add(ChocMilkQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 193, 71, -1));

        jlbdChShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdChShake.setForeground(new java.awt.Color(255, 255, 255));
        jlbdChShake.setText("Special Shake  500/=");
        Drink_Panel.add(jlbdChShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 159, 272, 28));

        jlbdVanShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdVanShake.setForeground(new java.awt.Color(255, 255, 255));
        jlbdVanShake.setText("Vanilla Milk Shake   250/=");
        Drink_Panel.add(jlbdVanShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, 247, 28));
        Drink_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 139, 102, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Desktop\\Resturant_Project\\src\\OopProject\\images\\coffee-2589759_640.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        Drink_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 230));

        getContentPane().add(Drink_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 128, 460, 250));

        Cost_panel.setBackground(new java.awt.Color(0, 102, 102));
        Cost_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        Cost_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbdCostMealText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdCostMealText.setForeground(new java.awt.Color(255, 255, 255));
        jlbdCostMealText.setText("Cost of Meal");
        Cost_panel.add(jlbdCostMealText, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 42, 160, 42));

        jlbdCostDrinkText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdCostDrinkText.setForeground(new java.awt.Color(255, 255, 255));
        jlbdCostDrinkText.setText("Cost of Drink");
        Cost_panel.add(jlbdCostDrinkText, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 160, 42));

        jlbdCostMadeText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdCostMadeText.setForeground(new java.awt.Color(255, 255, 255));
        jlbdCostMadeText.setText("Total Cost of Item");
        Cost_panel.add(jlbdCostMadeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 139, 178, 40));

        TotalCostShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalCostShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalCostShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCostShowActionPerformed(evt);
            }
        });
        Cost_panel.add(TotalCostShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 138, 166, 42));

        CostDrinkShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CostDrinkShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CostDrinkShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostDrinkShowActionPerformed(evt);
            }
        });
        Cost_panel.add(CostDrinkShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 90, 166, 42));

        CostMealShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CostMealShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CostMealShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostMealShowActionPerformed(evt);
            }
        });
        Cost_panel.add(CostMealShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 42, 166, 42));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Desktop\\Resturant_Project\\src\\OopProject\\images\\salmon-1312372_640.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        Cost_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 210));

        getContentPane().add(Cost_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 396, 481, 230));

        Payment_panel.setBackground(new java.awt.Color(0, 102, 102));
        Payment_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        Payment_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TaxShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TaxShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TaxShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxShowActionPerformed(evt);
            }
        });
        Payment_panel.add(TaxShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 42, 135, 42));

        SubTotalShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubTotalShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SubTotalShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTotalShowActionPerformed(evt);
            }
        });
        Payment_panel.add(SubTotalShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 90, 135, 42));

        TotalShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalShow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalShowActionPerformed(evt);
            }
        });
        Payment_panel.add(TotalShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 138, 135, 42));

        jlbdSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlbdSubTotal.setText("Sub Total");
        Payment_panel.add(jlbdSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 90, 160, 42));

        jlbdTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlbdTotal.setText("Total");
        Payment_panel.add(jlbdTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 139, 160, 40));

        jlbdTax2.setBackground(new java.awt.Color(0, 102, 102));
        jlbdTax2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbdTax2.setForeground(new java.awt.Color(255, 255, 255));
        jlbdTax2.setText("Tax");
        Payment_panel.add(jlbdTax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 42, 160, 42));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Desktop\\Resturant_Project\\src\\OopProject\\images\\restaurant-2618315_640.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        Payment_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 210));

        getContentPane().add(Payment_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 450, 230));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));

        Receipt_Panel.setColumns(20);
        Receipt_Panel.setRows(5);
        jScrollPane1.setViewportView(Receipt_Panel);

        jBut_Save.setBackground(new java.awt.Color(0, 102, 102));
        jBut_Save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBut_Save.setForeground(new java.awt.Color(255, 255, 255));
        jBut_Save.setText("Print Slip");
        jBut_Save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_Save.setBorderPainted(false);
        jBut_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jBut_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBut_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(978, 128, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBut_Total.setBackground(new java.awt.Color(0, 102, 102));
        jBut_Total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBut_Total.setForeground(new java.awt.Color(255, 255, 255));
        jBut_Total.setText("Total");
        jBut_Total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_Total.setBorderPainted(false);
        jBut_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_TotalActionPerformed(evt);
            }
        });
        jPanel7.add(jBut_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 23, 160, -1));

        jBut_Receipt.setBackground(new java.awt.Color(0, 102, 102));
        jBut_Receipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBut_Receipt.setForeground(new java.awt.Color(255, 255, 255));
        jBut_Receipt.setText("Receipt");
        jBut_Receipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_Receipt.setBorderPainted(false);
        jBut_Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ReceiptActionPerformed(evt);
            }
        });
        jPanel7.add(jBut_Receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 23, 160, -1));

        jBut_Reset.setBackground(new java.awt.Color(0, 102, 102));
        jBut_Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBut_Reset.setForeground(new java.awt.Color(255, 255, 255));
        jBut_Reset.setText("Reset");
        jBut_Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_Reset.setBorderPainted(false);
        jBut_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_ResetActionPerformed(evt);
            }
        });
        jPanel7.add(jBut_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 23, 160, -1));

        jBut_Back.setBackground(new java.awt.Color(0, 102, 102));
        jBut_Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBut_Back.setForeground(new java.awt.Color(255, 255, 255));
        jBut_Back.setText("Back");
        jBut_Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBut_Back.setBorderPainted(false);
        jBut_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_BackActionPerformed(evt);
            }
        });
        jPanel7.add(jBut_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 23, 165, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\MBG Traders\\Downloads\\eating-601581_1280.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 644, 920, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BurgerQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgerQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BurgerQtyActionPerformed

    private void BurgMealQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgMealQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BurgMealQtyActionPerformed

    private void ZingerQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZingerQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZingerQtyActionPerformed

    private void ChLegQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChLegQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChLegQtyActionPerformed

    private void BacCheQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacCheQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BacCheQtyActionPerformed

    private void MilkQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MilkQtyActionPerformed

    private void VanQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VanQtyActionPerformed

    private void ClasVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasVanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClasVanActionPerformed

    private void VanMilkQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VanMilkQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VanMilkQtyActionPerformed

    private void ChocMilkQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocMilkQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChocMilkQtyActionPerformed

    private void TaxShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxShowActionPerformed

    private void SubTotalShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTotalShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubTotalShowActionPerformed

    private void TotalShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalShowActionPerformed

    private void TotalCostShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalCostShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalCostShowActionPerformed

    private void CostDrinkShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostDrinkShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostDrinkShowActionPerformed

    private void CostMealShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostMealShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostMealShowActionPerformed

    private void jBut_ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ReceiptActionPerformed
       //======================================================================
        int refs = 1325 + (int)(Math.random()*4328);

        //======================================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        
        tTime.format(timer.getTime());
        
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        
        Tdate.format(timer.getTime());
        
        Receipt_Panel.append("\n"+"\t       BORSA RESTAURANT \n" + 
                "\n"+
                " References:\t\t\t" + refs +
                "\n====================================================\n" + 
                    " Meals:\t\t" + CostMealShow.getText()+ "\n\n"+
                    " Drinks:\t\t" + CostDrinkShow.getText()+ "\n\n"+
                    " Total Cost:\t\t" + TotalCostShow.getText()+ "\n\n"
                +
                "\n====================================================\n" + "\n\n" +
                
                " Tax:\t\t" + TaxShow.getText() + "\n\n" +
                " SubTotal:\t\t" + SubTotalShow.getText() + "\n\n" +
                " TotalShow:\t\t" + TotalShow.getText() + "\n\n" +
                
                "====================================================="+
                "\n\n" +
        
                "Order Date : " + Tdate.format(timer.getTime())+"\n\n" +
                "Order Time : " + tTime.format(timer.getTime())+
                
                "\n\n\n\t             THANK YOU ");

        
        
    }//GEN-LAST:event_jBut_ReceiptActionPerformed

    private void jBut_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_ResetActionPerformed

        
        
        //For Payment Receipt Reset Function//
        Receipt_Panel.setText(null);
       


        //For Payment Panel Reset
        JTextField clearText = (null);
        for (Component c: Payment_panel.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)c;
                clearText.setText("");                
            }
            
        }
        
        //For Cost Panel Reset Function//
        for (Component c: Cost_panel.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)c;
                clearText.setText("");                
            }
            
        }
        //For Meal Panel Reset Function//
        for (Component c: Meal_Panel.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)c;
                clearText.setText("0");                
            }
            
        }
        //For Drink Panel Reset Function//
        for (Component c: Drink_Panel.getComponents()) {
            if (c.getClass().toString().contains("javax.swing.JTextField")) {
                clearText = (JTextField)c;
                clearText.setText("0");                
            }
            
        }
        
        
    }//GEN-LAST:event_jBut_ResetActionPerformed

    private void jBut_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_TotalActionPerformed
         
        double iTax, iSubTotal , iTotal;
        
        SubClass_Child ItemCost = new SubClass_Child();
        ItemCost.ZingerBurger = ItemCost.pZingerBurger * Double .parseDouble(ZingerQty.getText());
        ItemCost.ZingerCheeseBurger = ItemCost.pZingerCheeseBurger * Double .parseDouble(BurgerQty.getText());
        ItemCost.ChickenCheeseBurger= ItemCost.pChickenCheeseBurger * Double .parseDouble(BurgMealQty.getText());
        ItemCost.ChickenLegend = ItemCost.pChickenLegend * Double .parseDouble(ChLegQty.getText());
        ItemCost.BaconAndCheeseBurger = ItemCost.pBaconAndCheeseBurger * Double .parseDouble(BacCheQty.getText());
        ItemCost.MilkShake = ItemCost.pMilkShake * Double .parseDouble(MilkQty.getText());
        ItemCost.SpecialOreoShake = ItemCost.pSpecialOreoShake * Double .parseDouble(VanQty.getText());
        ItemCost.VanMilkShake = ItemCost.pVanMilkShake * Double .parseDouble(VanMilkQty.getText());
        ItemCost.SpeciakShake = ItemCost.pSpeciakShake * Double .parseDouble(ClasVan.getText());
        
        iSubTotal = ItemCost.getAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        String SubTotal = String.format("%.2f Rs", iSubTotal);
        SubTotalShow.setText(SubTotal);
        
        String Tax = String.format("%.2f Rs", iTax);
        TaxShow.setText(Tax);
       
        String Total = String.format("%.2f Rs", iTotal);
        TotalShow.setText(Total);
        
        String Meal = String.format("%.2f Rs", ItemCost.Meals);
        CostMealShow.setText(Meal);
        
        String Drink = String.format("%.2f Rs", ItemCost.Drinks);
        CostDrinkShow.setText(Drink);

        String TotalS = String.format("%.2f Rs", ItemCost.TotalofMD);
        TotalCostShow.setText(TotalS);
        
        
    }//GEN-LAST:event_jBut_TotalActionPerformed

    private void jBut_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_BackActionPerformed
        Second_page sp = new Second_page();
        sp.show();
        this.dispose();
//   back on main page
//         TODO add your handling code here:
    }//GEN-LAST:event_jBut_BackActionPerformed

    private void jBut_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_SaveActionPerformed
        try {
            // TODO add your handling code here:

            Receipt_Panel.print();
        } catch (PrinterException ex) {
           
        }
    }//GEN-LAST:event_jBut_SaveActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Resturant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(() -> {
            new OO_Resturant().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BacCheQty;
    private javax.swing.JTextField BurgMealQty;
    private javax.swing.JTextField BurgerQty;
    private javax.swing.JTextField ChLegQty;
    private javax.swing.JTextField ChocMilkQty;
    private javax.swing.JTextField ClasVan;
    private javax.swing.JTextField CostDrinkShow;
    private javax.swing.JTextField CostMealShow;
    private javax.swing.JPanel Cost_panel;
    private javax.swing.JPanel Drink_Panel;
    private javax.swing.JPanel Meal_Panel;
    private javax.swing.JTextField MilkQty;
    private javax.swing.JPanel Payment_panel;
    private javax.swing.JTextArea Receipt_Panel;
    private javax.swing.JTextField SubTotalShow;
    private javax.swing.JTextField TaxShow;
    private javax.swing.JTextField TotalCostShow;
    private javax.swing.JTextField TotalShow;
    private javax.swing.JTextField VanMilkQty;
    private javax.swing.JTextField VanQty;
    private javax.swing.JTextField ZingerQty;
    private javax.swing.JButton jBut_Back;
    private javax.swing.JButton jBut_Receipt;
    private javax.swing.JButton jBut_Reset;
    private javax.swing.JButton jBut_Save;
    private javax.swing.JButton jBut_Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbdBurMeal;
    private javax.swing.JLabel jlbdChBurg;
    private javax.swing.JLabel jlbdChShake;
    private javax.swing.JLabel jlbdCheese;
    private javax.swing.JLabel jlbdChicLegend;
    private javax.swing.JLabel jlbdClassicVAn;
    private javax.swing.JLabel jlbdCostDrinkText;
    private javax.swing.JLabel jlbdCostMadeText;
    private javax.swing.JLabel jlbdCostMealText;
    private javax.swing.JLabel jlbdFish;
    private javax.swing.JLabel jlbdMilkShake;
    private javax.swing.JLabel jlbdSubTotal;
    private javax.swing.JLabel jlbdTax2;
    private javax.swing.JLabel jlbdTax3;
    private javax.swing.JLabel jlbdTax6;
    private javax.swing.JLabel jlbdTotal;
    private javax.swing.JLabel jlbdVanCone;
    private javax.swing.JLabel jlbdVanShake;
    // End of variables declaration//GEN-END:variables
}
